### ISSUE TITLE
Certificados

### ISSUE THREAD

**Issue by MarielsonM** [tchelinux/certificados#2]
Ao requisitar o certificado, clico em um dos links gerados e não sou direcionado a nenhuma página. Necessito dos certificados para fim de horas complementares. 
![Tchê](https://user-images.githubusercontent.com/79068333/107898319-33927080-6f1a-11eb-8535-2d3500490330.png)

**Comment by rjeffman** [comment]
@MarielsonM, o seu certificado pode ser validado a partir do endereço: https://certificados.tchelinux.org/?verify=8aa7d253e4522ed2527a2196765a05d0

Enquanto eu verifico porque seu certificado não está sendo gerado, você pode dizer qual é o seu browser e sistema operacional? E quais as versões dos dois?

**Comment by rafasgj** [comment]
@MarielsonM seu certificado pode ser validado em https://certificados.tchelinux.org/?verify=8aa7d253e4522ed2527a2196765a05d0

Enquanto eu verifico o motivo de você não conseguir gerar seu certificado, você pode me passar qual é o seu sistema operacional, qual o seu browser, e as versões de ambos?

**Comment by MarielsonM** [comment]
Utilizo o sistema operacional Windows 10 versão 20H2 e tentei com os navegadores Microsoft Edge Versão 90.0.789.1 e Google Chrome Versão 88.0.4324.150. Também tentei acessar via mobile através do sistema IOS pelo Safari e não obtive sucesso. 

Com o link recebido, acessei a validação do certificado mas continuo sem acesso ao mesmo.

**Comment by rafasgj** [comment]
@MarielsonM, desculpe a demora, mas os certificados foram corrigidos e você já pode obter seu certificado.
