### ISSUE TITLE
Problema com a emissão de certificado

### ISSUE THREAD

**Issue by augusto919** [tchelinux/certificados#3]
Não estou conseguindo emitir meu certificado no Tchelinux, eu digito meu e-mail(augustocrds.txr@gmail.com) e aparece a edição que eu participei tento clicar em cima mas não adianta nada, como eu faço para conseguir meu certificado?

**Comment by rafasgj** [comment]
@augusto919, desculpe a demora, mas os certitficados já foram corrigidos e você pode requisitar novamente o seu certificado.
