### ISSUE TITLE
Emissão de certificados digitais

### ISSUE THREAD

**Issue by wagner-inacio** [tchelinux/certificados#7]
Não estou conseguindo emitir os certificados de participação nos eventos. 
Quando insiro o e-mail cadastrado o sistema mostra os eventos vinculados. Quando abro não é carregado a página com o .pdf

![atestado](https://user-images.githubusercontent.com/41226412/122270965-43fd2c80-ceb5-11eb-9fc3-5df4792033df.png)

**Comment by rafasgj** [comment]
@wagnerinacio16, obrigado por nos avisar do problema.

Seu  certificado já pode ser gerado.
